"""delpi module"""

module(name = "delpi")

#################################################################################
# Available dependencies from the Bazel registry (https://registry.bazel.build/)
#################################################################################

# Apache License 2.0 | rules_cc for building C++ libraries with Bazel
bazel_dep(name = "rules_cc", version = "0.2.18")

# Apache License 2.0 | rules_foreign_cc for building C++ libraries with other build systems
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")

# Apache License 2.0 | utility rules for Bazel
bazel_dep(name = "bazel_skylib", version = "1.9.0")

# Apache License 2.0 | Bazel rules for packaging the project
bazel_dep(name = "rules_pkg", version = "1.2.0")

# Apache License 2.0 | rules_python for building python targets
bazel_dep(name = "rules_python", version = "1.9.0")

# MIT | argparse implementation for modern C++
bazel_dep(name = "argparse", version = "3.2.0")

# MIT | C++ library for formatting text
bazel_dep(name = "fmt", version = "11.2.0")

# MIT | logging library
bazel_dep(name = "spdlog", version = "1.17.0")

# https://github.com/madler/zlib/blob/develop/LICENSE | zlib compression library
bazel_dep(name = "zlib", version = "1.3.1.bcr.3")

# https://github.com/libarchive/bzip2/blob/master/COPYING | Compression library
bazel_dep(name = "bzip2", version = "1.0.8")

# Mozilla Public License 2.0 | C++ library that handles matrices and vectors
bazel_dep(name = "eigen", version = "5.0.1.bcr.1")

# MIT | c++ library for arbitrary precision arithmetic
bazel_dep(name = "mpfr", version = "4.2.2")

# Apache License 2.0 | Integration of Boost into Bazel
bazel_dep(name = "boost.multiprecision", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.interprocess", version = "1.90.0.bcr.1")

# GNU Lesser General Public License v3.0 | arbitrary precision arithmetic library
bazel_dep(name = "gmp", version = "6.3.0.bcr.1")

# Apache License 2.0 | exact linear programming solver
bazel_dep(name = "soplex", version = "7.1.4.bcr.4")
single_version_override(
    module_name = "soplex",
    patches = ["third_party/soplex.patch"],
)

# https://github.com/pybind/pybind11_bazel/blob/master/LICENSE | pybind11 for binding C++ and Python
bazel_dep(name = "pybind11_bazel", version = "3.0.1")

# MIT | rules for dealing with target dependencies
bazel_dep(name = "depend_on_what_you_use", version = "0.16.0", dev_dependency = True)

# https://github.com/cpplint/cpplint/blob/develop/LICENSE | Google C++ Style Guide
bazel_dep(name = "cpplint", version = "2.0.2", dev_dependency = True)

# BSD-3-Clause license | C++ test suite by Google
bazel_dep(name = "googletest", version = "1.17.0", dev_dependency = True)

# BSD-3-Clause license | Benchmarking library by Google
bazel_dep(name = "google_benchmark", version = "1.9.5", dev_dependency = True)

# Apache License 2.0 | Doxygen documentation generator
bazel_dep(name = "rules_doxygen", version = "2.6.3", dev_dependency = True)

#################################################################################
# External dependencies not available in the Bazel registry
#################################################################################

# GitHub repositories

github_archive = use_repo_rule("//tools:git_archive.bzl", "github_archive")

# GNU General Public License v3.0 | delta-complete linear programming solver
github_archive(
    name = "qsopt_ex",
    build_file = "//third_party:qsopt_ex.BUILD.bazel",
    commit = "dcfac765728466dc725a344d0432f07535ccb081",
    repository = "TendTo/qsopt-ex",
    sha256 = "6aaadc88952fbd536799060928ddd3239b06a42130796a1117d683fbb297fd44",
)

#################################################################################
# Load module extensions
#################################################################################

PYTHON_VERSIONS = [
    "3.9",
    "3.10",
    "3.11",
    "3.12",
    "3.13",
    "3.14",
]

python = use_extension("@rules_python//python/extensions:python.bzl", "python")

[
    python.toolchain(python_version = v)
    for v in PYTHON_VERSIONS
]

use_repo(
    python,
    "python_3_10",
    "python_3_11",
    "python_3_12",
    "python_3_13",
    "python_3_14",
    "python_3_9",
    "python_versions",
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")

[
    pip.parse(
        hub_name = "pypi",
        python_version = v,
        requirements_lock = "//tools:requirements.txt",
    )
    for v in PYTHON_VERSIONS
]

use_repo(pip, "pypi")

doxygen_extension = use_extension("@rules_doxygen//:extensions.bzl", "doxygen_extension")
use_repo(doxygen_extension, "doxygen")
