"""
Exact LP solver with support for delta relaxation
"""
from __future__ import annotations
import collections.abc
import typing
__all__ = ['Column', 'Config', 'Expression', 'Format', 'Formula', 'FormulaKind', 'LOG_CRITICAL', 'LOG_DEBUG', 'LOG_ERROR', 'LOG_INFO', 'LOG_NONE', 'LOG_TRACE', 'LOG_WARN', 'LpMode', 'LpResult', 'LpSolver', 'LpSolverName', 'Row', 'Variable', 'set_verbosity']
class Column:
    lb: float | None
    obj: float | None
    ub: float | None
    var: Variable
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
class Config:
    continuous_output: bool
    csv: bool
    debug_parsing: bool
    filename: str
    format: Format
    lp_mode: LpMode
    lp_solver: LpSolverName
    produce_model: bool
    read_from_stdin: bool
    silent: bool
    skip_optimise: bool
    verify: bool
    with_timings: bool
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    @staticmethod
    def from_args(args: collections.abc.Sequence[str]) -> Config:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, filename: str = '', continuous_output: bool = False, csv: bool = False, debug_parsing: bool = False, delta: typing.SupportsFloat = 0.0, format: Format = ..., lp_mode: LpMode = ..., lp_solver: LpSolverName = ..., number_of_jobs: typing.SupportsInt = 1, skip_optimise: bool = False, dry_run: bool = False, produce_models: bool = False, random_seed: typing.SupportsInt = 0, read_from_stdin: bool = False, silent: bool = False, verbose_delpi: typing.SupportsInt = 2, verbose_simplex: typing.SupportsInt = 0, verify: bool = False, with_timings: bool = False) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    @property
    def delta(self) -> float:
        ...
    @delta.setter
    def delta(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def number_of_jobs(self) -> int:
        ...
    @number_of_jobs.setter
    def number_of_jobs(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def random_seed(self) -> int:
        ...
    @random_seed.setter
    def random_seed(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def verbose_delpi(self) -> int:
        ...
    @verbose_delpi.setter
    def verbose_delpi(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def verbose_simplex(self) -> int:
        ...
    @verbose_simplex.setter
    def verbose_simplex(self, arg1: typing.SupportsInt) -> None:
        ...
class Expression:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    @typing.overload
    def __add__(self, arg0: Expression) -> Expression:
        ...
    @typing.overload
    def __add__(self, arg0: Variable) -> Expression:
        ...
    @typing.overload
    def __eq__(self, arg0: Expression) -> Formula:
        ...
    @typing.overload
    def __eq__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __eq__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    @typing.overload
    def __ge__(self, arg0: Expression) -> Formula:
        ...
    @typing.overload
    def __ge__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __ge__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    @typing.overload
    def __gt__(self, arg0: Expression) -> Formula:
        ...
    @typing.overload
    def __gt__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __gt__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __iadd__(self, arg0: Expression) -> Expression:
        ...
    @typing.overload
    def __iadd__(self, arg0: Variable) -> Expression:
        ...
    def __imul__(self, arg0: typing.SupportsFloat) -> Expression:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, var: Variable) -> None:
        ...
    @typing.overload
    def __init__(self, addends: collections.abc.Mapping[Variable, float]) -> None:
        ...
    @typing.overload
    def __init__(self, expression: Expression) -> None:
        ...
    @typing.overload
    def __isub__(self, arg0: Expression) -> Expression:
        ...
    @typing.overload
    def __isub__(self, arg0: Variable) -> Expression:
        ...
    def __itruediv__(self, arg0: typing.SupportsFloat) -> Expression:
        ...
    @typing.overload
    def __le__(self, arg0: Expression) -> Formula:
        ...
    @typing.overload
    def __le__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __le__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    @typing.overload
    def __lt__(self, arg0: Expression) -> Formula:
        ...
    @typing.overload
    def __lt__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __lt__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    def __mul__(self, arg0: typing.SupportsFloat) -> Expression:
        ...
    @typing.overload
    def __ne__(self, arg0: Expression) -> Formula:
        ...
    @typing.overload
    def __ne__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __ne__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    def __neg__(self) -> Expression:
        ...
    def __pos__(self) -> Expression:
        ...
    def __radd__(self, arg0: Variable) -> Expression:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat) -> Expression:
        ...
    def __rsub__(self, arg0: Variable) -> Expression:
        ...
    def __str__(self) -> str:
        ...
    @typing.overload
    def __sub__(self, arg0: Expression) -> Expression:
        ...
    @typing.overload
    def __sub__(self, arg0: Variable) -> Expression:
        ...
    def __truediv__(self, arg0: typing.SupportsFloat) -> Expression:
        ...
    def add(self, var: Variable, coeff: float) -> Expression:
        ...
    def copy(self) -> Expression:
        ...
    def equal_to(self, o: Expression) -> bool:
        ...
    def evaluate(self, env: collections.abc.Mapping[Variable, float]) -> float:
        ...
    def less(self, o: Expression) -> bool:
        ...
    def substitute(self, expr_subst: collections.abc.Mapping[Variable, Variable]) -> Expression:
        ...
    def subtract(self, var: Variable, coeff: float) -> Expression:
        ...
    @property
    def addends(self) -> dict[Variable, float]:
        ...
    @property
    def use_count(self) -> int:
        ...
    @property
    def variables(self) -> list[Variable]:
        ...
class Format:
    """
    Members:
    
      AUTO
    
      MPS
    
      LP
    """
    AUTO: typing.ClassVar[Format]  # value = <Format.AUTO: 0>
    LP: typing.ClassVar[Format]  # value = <Format.LP: 2>
    MPS: typing.ClassVar[Format]  # value = <Format.MPS: 1>
    __members__: typing.ClassVar[dict[str, Format]]  # value = {'AUTO': <Format.AUTO: 0>, 'MPS': <Format.MPS: 1>, 'LP': <Format.LP: 2>}
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Formula:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __eq__(self, arg0: Formula) -> bool:
        ...
    def __ge__(self, arg0: Formula) -> bool:
        ...
    def __gt__(self, arg0: Formula) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __init__(self, lhs: Expression, kind: FormulaKind, rhs: typing.SupportsFloat) -> None:
        ...
    def __le__(self, arg0: Formula) -> bool:
        ...
    def __lt__(self, arg0: Formula) -> bool:
        ...
    def __ne__(self, arg0: Formula) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def copy(self: Expression) -> Expression:
        ...
    def equal_to(self, o: Formula) -> bool:
        ...
    def evaluate(self, env: collections.abc.Mapping[Variable, float]) -> bool:
        ...
    def less(self, o: Formula) -> bool:
        ...
    def substitute(self, expr_subst: collections.abc.Mapping[Variable, Variable]) -> Formula:
        ...
    @property
    def expression(self) -> Expression:
        ...
    @property
    def kind(self) -> FormulaKind:
        ...
    @property
    def rhs(self) -> float:
        ...
    @property
    def variables(self) -> list[Variable]:
        ...
class FormulaKind:
    """
    Members:
    
      EQ
    
      NEQ
    
      GT
    
      GEQ
    
      LT
    
      LEQ
    """
    EQ: typing.ClassVar[FormulaKind]  # value = <FormulaKind.EQ: 0>
    GEQ: typing.ClassVar[FormulaKind]  # value = <FormulaKind.GEQ: 3>
    GT: typing.ClassVar[FormulaKind]  # value = <FormulaKind.GT: 2>
    LEQ: typing.ClassVar[FormulaKind]  # value = <FormulaKind.LEQ: 5>
    LT: typing.ClassVar[FormulaKind]  # value = <FormulaKind.LT: 4>
    NEQ: typing.ClassVar[FormulaKind]  # value = <FormulaKind.NEQ: 1>
    __members__: typing.ClassVar[dict[str, FormulaKind]]  # value = {'EQ': <FormulaKind.EQ: 0>, 'NEQ': <FormulaKind.NEQ: 1>, 'GT': <FormulaKind.GT: 2>, 'GEQ': <FormulaKind.GEQ: 3>, 'LT': <FormulaKind.LT: 4>, 'LEQ': <FormulaKind.LEQ: 5>}
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class LpMode:
    """
    Members:
    
      AUTO
    
      PURE_PRECISION_BOOSTING
    
      PURE_ITERATIVE_REFINEMENT
    
      HYBRID
    """
    AUTO: typing.ClassVar[LpMode]  # value = <LpMode.AUTO: 0>
    HYBRID: typing.ClassVar[LpMode]  # value = <LpMode.HYBRID: 3>
    PURE_ITERATIVE_REFINEMENT: typing.ClassVar[LpMode]  # value = <LpMode.PURE_ITERATIVE_REFINEMENT: 2>
    PURE_PRECISION_BOOSTING: typing.ClassVar[LpMode]  # value = <LpMode.PURE_PRECISION_BOOSTING: 1>
    __members__: typing.ClassVar[dict[str, LpMode]]  # value = {'AUTO': <LpMode.AUTO: 0>, 'PURE_PRECISION_BOOSTING': <LpMode.PURE_PRECISION_BOOSTING: 1>, 'PURE_ITERATIVE_REFINEMENT': <LpMode.PURE_ITERATIVE_REFINEMENT: 2>, 'HYBRID': <LpMode.HYBRID: 3>}
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class LpResult:
    """
    Members:
    
      OPTIMAL
    
      DELTA_OPTIMAL
    
      UNBOUNDED
    
      INFEASIBLE
    
      ERROR
    
      UNSOLVED
    """
    DELTA_OPTIMAL: typing.ClassVar[LpResult]  # value = <LpResult.DELTA_OPTIMAL: 2>
    ERROR: typing.ClassVar[LpResult]  # value = <LpResult.ERROR: 5>
    INFEASIBLE: typing.ClassVar[LpResult]  # value = <LpResult.INFEASIBLE: 4>
    OPTIMAL: typing.ClassVar[LpResult]  # value = <LpResult.OPTIMAL: 1>
    UNBOUNDED: typing.ClassVar[LpResult]  # value = <LpResult.UNBOUNDED: 3>
    UNSOLVED: typing.ClassVar[LpResult]  # value = <LpResult.UNSOLVED: 0>
    __members__: typing.ClassVar[dict[str, LpResult]]  # value = {'OPTIMAL': <LpResult.OPTIMAL: 1>, 'DELTA_OPTIMAL': <LpResult.DELTA_OPTIMAL: 2>, 'UNBOUNDED': <LpResult.UNBOUNDED: 3>, 'INFEASIBLE': <LpResult.INFEASIBLE: 4>, 'ERROR': <LpResult.ERROR: 5>, 'UNSOLVED': <LpResult.UNSOLVED: 0>}
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class LpSolver:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    @staticmethod
    def get_instance(config: Config) -> LpSolver:
        ...
    @typing.overload
    def add_column(self, column: Variable) -> int:
        ...
    @typing.overload
    def add_column(self, column: Variable, obj: float) -> int:
        ...
    @typing.overload
    def add_column(self, column: Variable, lb: float, ub: float) -> int:
        ...
    @typing.overload
    def add_column(self, column: Variable, obj: float, lb: float, ub: float) -> int:
        ...
    @typing.overload
    def add_row(self, formula: Formula) -> int:
        ...
    @typing.overload
    def add_row(self, formula: Expression, kind: FormulaKind, rhs: float) -> int:
        ...
    def column(self, column_idx: typing.SupportsInt) -> Column:
        ...
    def dual_solution(self) -> list[float]:
        ...
    def parse(self) -> bool:
        ...
    def parse_file(self, filename: str) -> bool:
        ...
    def parse_string(self, input: str) -> bool:
        ...
    def row(self, row_idx: typing.SupportsInt) -> Row:
        ...
    @typing.overload
    def solution(self) -> list[float]:
        ...
    @typing.overload
    def solution(self, arg0: Variable) -> float:
        ...
    def solve(self) -> LpResult:
        ...
    def var(self, column_idx: typing.SupportsInt) -> Variable:
        ...
    @property
    def config(self) -> Config:
        ...
    @property
    def constraints(self) -> list[Formula]:
        ...
    @property
    def infinity(self) -> float:
        ...
    @property
    def ninfinity(self) -> float:
        ...
    @property
    def num_columns(self) -> int:
        ...
    @property
    def num_rows(self) -> int:
        ...
    @property
    def variables(self) -> list[Variable]:
        ...
class LpSolverName:
    """
    Members:
    
      QSOPTEX
    
      SOPLEX
    """
    QSOPTEX: typing.ClassVar[LpSolverName]  # value = <LpSolverName.QSOPTEX: 1>
    SOPLEX: typing.ClassVar[LpSolverName]  # value = <LpSolverName.SOPLEX: 0>
    __members__: typing.ClassVar[dict[str, LpSolverName]]  # value = {'QSOPTEX': <LpSolverName.QSOPTEX: 1>, 'SOPLEX': <LpSolverName.SOPLEX: 0>}
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Row:
    lb: float | None
    ub: float | None
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    @property
    def addends(self) -> list[tuple[Variable, float]]:
        ...
    @addends.setter
    def addends(self, arg0: collections.abc.Sequence[tuple[Variable, float]]) -> None:
        ...
class Variable:
    dummy_id: typing.ClassVar[int] = 18446744073709551615
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __add__(self, arg0: Variable) -> Expression:
        ...
    @typing.overload
    def __eq__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __eq__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    @typing.overload
    def __ge__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __ge__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    @typing.overload
    def __gt__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __gt__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, name: str) -> None:
        ...
    @typing.overload
    def __le__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __le__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    @typing.overload
    def __lt__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __lt__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    def __mul__(self, arg0: typing.SupportsFloat) -> Expression:
        ...
    @typing.overload
    def __ne__(self, arg0: Variable) -> Formula:
        ...
    @typing.overload
    def __ne__(self, arg0: typing.SupportsFloat) -> Formula:
        ...
    def __neg__(self) -> Expression:
        ...
    def __pos__(self) -> Variable:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat) -> Expression:
        ...
    def __str__(self) -> str:
        ...
    def __sub__(self, arg0: Variable) -> Expression:
        ...
    def __truediv__(self, arg0: typing.SupportsFloat) -> Expression:
        ...
    def equal_to(self, o: Variable) -> bool:
        ...
    def less(self, o: Variable) -> bool:
        ...
    @property
    def id(self) -> int:
        ...
    @property
    def is_dummy(self) -> bool:
        ...
    @property
    def name(self) -> str:
        ...
def set_verbosity(arg0: typing.SupportsInt) -> None:
    ...
LOG_CRITICAL: int = 0
LOG_DEBUG: int = 4
LOG_ERROR: int = 1
LOG_INFO: int = 3
LOG_NONE: int = -1
LOG_TRACE: int = 5
LOG_WARN: int = 2
__version__: str = '0.0.1'
